package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class Album {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.album_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String albumName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.album_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String albumType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String publishStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String checkStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer viewPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer commentPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column album.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String commentAnonymityFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.rec_id
	 * @return  the value of album.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.rec_id
	 * @param recId  the value for album.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.album_name
	 * @return  the value of album.album_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAlbumName() {
		return albumName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.album_name
	 * @param albumName  the value for album.album_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAlbumName(String albumName) {
		this.albumName = albumName == null ? null : albumName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.album_type
	 * @return  the value of album.album_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAlbumType() {
		return albumType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.album_type
	 * @param albumType  the value for album.album_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAlbumType(String albumType) {
		this.albumType = albumType == null ? null : albumType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.publish_status
	 * @return  the value of album.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getPublishStatus() {
		return publishStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.publish_status
	 * @param publishStatus  the value for album.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPublishStatus(String publishStatus) {
		this.publishStatus = publishStatus == null ? null : publishStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.check_status
	 * @return  the value of album.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCheckStatus() {
		return checkStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.check_status
	 * @param checkStatus  the value for album.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus == null ? null : checkStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.user_id
	 * @return  the value of album.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.user_id
	 * @param userId  the value for album.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.add_time
	 * @return  the value of album.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.add_time
	 * @param addTime  the value for album.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.check_time
	 * @return  the value of album.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.check_time
	 * @param checkTime  the value for album.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.view_popedom
	 * @return  the value of album.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getViewPopedom() {
		return viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.view_popedom
	 * @param viewPopedom  the value for album.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setViewPopedom(Integer viewPopedom) {
		this.viewPopedom = viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.comment_popedom
	 * @return  the value of album.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getCommentPopedom() {
		return commentPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.comment_popedom
	 * @param commentPopedom  the value for album.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentPopedom(Integer commentPopedom) {
		this.commentPopedom = commentPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column album.comment_anonymity_flag
	 * @return  the value of album.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCommentAnonymityFlag() {
		return commentAnonymityFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column album.comment_anonymity_flag
	 * @param commentAnonymityFlag  the value for album.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentAnonymityFlag(String commentAnonymityFlag) {
		this.commentAnonymityFlag = commentAnonymityFlag == null ? null
				: commentAnonymityFlag.trim();
	}
}