package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlbumExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public AlbumExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecIdIsNull() {
			addCriterion("rec_id is null");
			return (Criteria) this;
		}

		public Criteria andRecIdIsNotNull() {
			addCriterion("rec_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecIdEqualTo(Long value) {
			addCriterion("rec_id =", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotEqualTo(Long value) {
			addCriterion("rec_id <>", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThan(Long value) {
			addCriterion("rec_id >", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThanOrEqualTo(Long value) {
			addCriterion("rec_id >=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThan(Long value) {
			addCriterion("rec_id <", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThanOrEqualTo(Long value) {
			addCriterion("rec_id <=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdIn(List<Long> values) {
			addCriterion("rec_id in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotIn(List<Long> values) {
			addCriterion("rec_id not in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdBetween(Long value1, Long value2) {
			addCriterion("rec_id between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotBetween(Long value1, Long value2) {
			addCriterion("rec_id not between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andAlbumNameIsNull() {
			addCriterion("album_name is null");
			return (Criteria) this;
		}

		public Criteria andAlbumNameIsNotNull() {
			addCriterion("album_name is not null");
			return (Criteria) this;
		}

		public Criteria andAlbumNameEqualTo(String value) {
			addCriterion("album_name =", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameNotEqualTo(String value) {
			addCriterion("album_name <>", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameGreaterThan(String value) {
			addCriterion("album_name >", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameGreaterThanOrEqualTo(String value) {
			addCriterion("album_name >=", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameLessThan(String value) {
			addCriterion("album_name <", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameLessThanOrEqualTo(String value) {
			addCriterion("album_name <=", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameLike(String value) {
			addCriterion("album_name like", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameNotLike(String value) {
			addCriterion("album_name not like", value, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameIn(List<String> values) {
			addCriterion("album_name in", values, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameNotIn(List<String> values) {
			addCriterion("album_name not in", values, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameBetween(String value1, String value2) {
			addCriterion("album_name between", value1, value2, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumNameNotBetween(String value1, String value2) {
			addCriterion("album_name not between", value1, value2, "albumName");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeIsNull() {
			addCriterion("album_type is null");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeIsNotNull() {
			addCriterion("album_type is not null");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeEqualTo(String value) {
			addCriterion("album_type =", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeNotEqualTo(String value) {
			addCriterion("album_type <>", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeGreaterThan(String value) {
			addCriterion("album_type >", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeGreaterThanOrEqualTo(String value) {
			addCriterion("album_type >=", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeLessThan(String value) {
			addCriterion("album_type <", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeLessThanOrEqualTo(String value) {
			addCriterion("album_type <=", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeLike(String value) {
			addCriterion("album_type like", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeNotLike(String value) {
			addCriterion("album_type not like", value, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeIn(List<String> values) {
			addCriterion("album_type in", values, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeNotIn(List<String> values) {
			addCriterion("album_type not in", values, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeBetween(String value1, String value2) {
			addCriterion("album_type between", value1, value2, "albumType");
			return (Criteria) this;
		}

		public Criteria andAlbumTypeNotBetween(String value1, String value2) {
			addCriterion("album_type not between", value1, value2, "albumType");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNull() {
			addCriterion("publish_status is null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNotNull() {
			addCriterion("publish_status is not null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusEqualTo(String value) {
			addCriterion("publish_status =", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotEqualTo(String value) {
			addCriterion("publish_status <>", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThan(String value) {
			addCriterion("publish_status >", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThanOrEqualTo(String value) {
			addCriterion("publish_status >=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThan(String value) {
			addCriterion("publish_status <", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThanOrEqualTo(String value) {
			addCriterion("publish_status <=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLike(String value) {
			addCriterion("publish_status like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotLike(String value) {
			addCriterion("publish_status not like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIn(List<String> values) {
			addCriterion("publish_status in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotIn(List<String> values) {
			addCriterion("publish_status not in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusBetween(String value1, String value2) {
			addCriterion("publish_status between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotBetween(String value1, String value2) {
			addCriterion("publish_status not between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIsNull() {
			addCriterion("check_status is null");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIsNotNull() {
			addCriterion("check_status is not null");
			return (Criteria) this;
		}

		public Criteria andCheckStatusEqualTo(String value) {
			addCriterion("check_status =", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotEqualTo(String value) {
			addCriterion("check_status <>", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusGreaterThan(String value) {
			addCriterion("check_status >", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusGreaterThanOrEqualTo(String value) {
			addCriterion("check_status >=", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusLessThan(String value) {
			addCriterion("check_status <", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusLessThanOrEqualTo(String value) {
			addCriterion("check_status <=", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusLike(String value) {
			addCriterion("check_status like", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotLike(String value) {
			addCriterion("check_status not like", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIn(List<String> values) {
			addCriterion("check_status in", values, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotIn(List<String> values) {
			addCriterion("check_status not in", values, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusBetween(String value1, String value2) {
			addCriterion("check_status between", value1, value2, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotBetween(String value1, String value2) {
			addCriterion("check_status not between", value1, value2,
					"checkStatus");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIsNull() {
			addCriterion("check_time is null");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIsNotNull() {
			addCriterion("check_time is not null");
			return (Criteria) this;
		}

		public Criteria andCheckTimeEqualTo(Date value) {
			addCriterion("check_time =", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotEqualTo(Date value) {
			addCriterion("check_time <>", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeGreaterThan(Date value) {
			addCriterion("check_time >", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("check_time >=", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeLessThan(Date value) {
			addCriterion("check_time <", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeLessThanOrEqualTo(Date value) {
			addCriterion("check_time <=", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIn(List<Date> values) {
			addCriterion("check_time in", values, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotIn(List<Date> values) {
			addCriterion("check_time not in", values, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeBetween(Date value1, Date value2) {
			addCriterion("check_time between", value1, value2, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotBetween(Date value1, Date value2) {
			addCriterion("check_time not between", value1, value2, "checkTime");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNull() {
			addCriterion("view_popedom is null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNotNull() {
			addCriterion("view_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomEqualTo(Integer value) {
			addCriterion("view_popedom =", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotEqualTo(Integer value) {
			addCriterion("view_popedom <>", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThan(Integer value) {
			addCriterion("view_popedom >", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_popedom >=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThan(Integer value) {
			addCriterion("view_popedom <", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThanOrEqualTo(Integer value) {
			addCriterion("view_popedom <=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIn(List<Integer> values) {
			addCriterion("view_popedom in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotIn(List<Integer> values) {
			addCriterion("view_popedom not in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom between", value1, value2, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom not between", value1, value2,
					"viewPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNull() {
			addCriterion("comment_popedom is null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNotNull() {
			addCriterion("comment_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomEqualTo(Integer value) {
			addCriterion("comment_popedom =", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotEqualTo(Integer value) {
			addCriterion("comment_popedom <>", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThan(Integer value) {
			addCriterion("comment_popedom >", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_popedom >=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThan(Integer value) {
			addCriterion("comment_popedom <", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThanOrEqualTo(Integer value) {
			addCriterion("comment_popedom <=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIn(List<Integer> values) {
			addCriterion("comment_popedom in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotIn(List<Integer> values) {
			addCriterion("comment_popedom not in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomBetween(Integer value1, Integer value2) {
			addCriterion("comment_popedom between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotBetween(Integer value1,
				Integer value2) {
			addCriterion("comment_popedom not between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIsNull() {
			addCriterion("comment_anonymity_flag is null");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIsNotNull() {
			addCriterion("comment_anonymity_flag is not null");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagEqualTo(String value) {
			addCriterion("comment_anonymity_flag =", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotEqualTo(String value) {
			addCriterion("comment_anonymity_flag <>", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagGreaterThan(String value) {
			addCriterion("comment_anonymity_flag >", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagGreaterThanOrEqualTo(String value) {
			addCriterion("comment_anonymity_flag >=", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLessThan(String value) {
			addCriterion("comment_anonymity_flag <", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLessThanOrEqualTo(String value) {
			addCriterion("comment_anonymity_flag <=", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLike(String value) {
			addCriterion("comment_anonymity_flag like", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotLike(String value) {
			addCriterion("comment_anonymity_flag not like", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIn(List<String> values) {
			addCriterion("comment_anonymity_flag in", values,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotIn(List<String> values) {
			addCriterion("comment_anonymity_flag not in", values,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagBetween(String value1,
				String value2) {
			addCriterion("comment_anonymity_flag between", value1, value2,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotBetween(String value1,
				String value2) {
			addCriterion("comment_anonymity_flag not between", value1, value2,
					"commentAnonymityFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table album
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table album
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 14 20:05:40 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}