package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String articleTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.seo_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String seoTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.seo_keyword
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String seoKeyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.seo_desc
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String seoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.tag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer articleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.author
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.source_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String sourceFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.source_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String sourceUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String anonymityFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String publishStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer checkStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer viewPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String commentPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.publish_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date publishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.checker_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String checkerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.updater_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String updaterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.article_content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String articleContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_id
	 * @return  the value of article.article_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_id
	 * @param articleId  the value for article.article_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setArticleId(Long articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.user_id
	 * @return  the value of article.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.user_id
	 * @param userId  the value for article.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_title
	 * @return  the value of article.article_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getArticleTitle() {
		return articleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_title
	 * @param articleTitle  the value for article.article_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle == null ? null : articleTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.seo_title
	 * @return  the value of article.seo_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getSeoTitle() {
		return seoTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.seo_title
	 * @param seoTitle  the value for article.seo_title
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setSeoTitle(String seoTitle) {
		this.seoTitle = seoTitle == null ? null : seoTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.seo_keyword
	 * @return  the value of article.seo_keyword
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getSeoKeyword() {
		return seoKeyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.seo_keyword
	 * @param seoKeyword  the value for article.seo_keyword
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setSeoKeyword(String seoKeyword) {
		this.seoKeyword = seoKeyword == null ? null : seoKeyword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.seo_desc
	 * @return  the value of article.seo_desc
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getSeoDesc() {
		return seoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.seo_desc
	 * @param seoDesc  the value for article.seo_desc
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setSeoDesc(String seoDesc) {
		this.seoDesc = seoDesc == null ? null : seoDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.tag
	 * @return  the value of article.tag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.tag
	 * @param tag  the value for article.tag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setTag(String tag) {
		this.tag = tag == null ? null : tag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_type
	 * @return  the value of article.article_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getArticleType() {
		return articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_type
	 * @param articleType  the value for article.article_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setArticleType(Integer articleType) {
		this.articleType = articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.author
	 * @return  the value of article.author
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.author
	 * @param author  the value for article.author
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.source_from
	 * @return  the value of article.source_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getSourceFrom() {
		return sourceFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.source_from
	 * @param sourceFrom  the value for article.source_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setSourceFrom(String sourceFrom) {
		this.sourceFrom = sourceFrom == null ? null : sourceFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.source_url
	 * @return  the value of article.source_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getSourceUrl() {
		return sourceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.source_url
	 * @param sourceUrl  the value for article.source_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setSourceUrl(String sourceUrl) {
		this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.anonymity_flag
	 * @return  the value of article.anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAnonymityFlag() {
		return anonymityFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.anonymity_flag
	 * @param anonymityFlag  the value for article.anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAnonymityFlag(String anonymityFlag) {
		this.anonymityFlag = anonymityFlag == null ? null : anonymityFlag
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.publish_status
	 * @return  the value of article.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getPublishStatus() {
		return publishStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.publish_status
	 * @param publishStatus  the value for article.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPublishStatus(String publishStatus) {
		this.publishStatus = publishStatus == null ? null : publishStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.check_status
	 * @return  the value of article.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getCheckStatus() {
		return checkStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.check_status
	 * @param checkStatus  the value for article.check_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.view_popedom
	 * @return  the value of article.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getViewPopedom() {
		return viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.view_popedom
	 * @param viewPopedom  the value for article.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setViewPopedom(Integer viewPopedom) {
		this.viewPopedom = viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.comment_popedom
	 * @return  the value of article.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCommentPopedom() {
		return commentPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.comment_popedom
	 * @param commentPopedom  the value for article.comment_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentPopedom(String commentPopedom) {
		this.commentPopedom = commentPopedom == null ? null : commentPopedom
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.publish_time
	 * @return  the value of article.publish_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getPublishTime() {
		return publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.publish_time
	 * @param publishTime  the value for article.publish_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.update_time
	 * @return  the value of article.update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.update_time
	 * @param updateTime  the value for article.update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.check_time
	 * @return  the value of article.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.check_time
	 * @param checkTime  the value for article.check_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.checker_name
	 * @return  the value of article.checker_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCheckerName() {
		return checkerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.checker_name
	 * @param checkerName  the value for article.checker_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCheckerName(String checkerName) {
		this.checkerName = checkerName == null ? null : checkerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.updater_name
	 * @return  the value of article.updater_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUpdaterName() {
		return updaterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.updater_name
	 * @param updaterName  the value for article.updater_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUpdaterName(String updaterName) {
		this.updaterName = updaterName == null ? null : updaterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.adder_name
	 * @return  the value of article.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.adder_name
	 * @param adderName  the value for article.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.article_content
	 * @return  the value of article.article_content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getArticleContent() {
		return articleContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.article_content
	 * @param articleContent  the value for article.article_content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent == null ? null : articleContent
				.trim();
	}
}