package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public ArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andArticleIdIsNull() {
			addCriterion("article_id is null");
			return (Criteria) this;
		}

		public Criteria andArticleIdIsNotNull() {
			addCriterion("article_id is not null");
			return (Criteria) this;
		}

		public Criteria andArticleIdEqualTo(Long value) {
			addCriterion("article_id =", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotEqualTo(Long value) {
			addCriterion("article_id <>", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThan(Long value) {
			addCriterion("article_id >", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("article_id >=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThan(Long value) {
			addCriterion("article_id <", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThanOrEqualTo(Long value) {
			addCriterion("article_id <=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdIn(List<Long> values) {
			addCriterion("article_id in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotIn(List<Long> values) {
			addCriterion("article_id not in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdBetween(Long value1, Long value2) {
			addCriterion("article_id between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotBetween(Long value1, Long value2) {
			addCriterion("article_id not between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andArticleTitleIsNull() {
			addCriterion("article_title is null");
			return (Criteria) this;
		}

		public Criteria andArticleTitleIsNotNull() {
			addCriterion("article_title is not null");
			return (Criteria) this;
		}

		public Criteria andArticleTitleEqualTo(String value) {
			addCriterion("article_title =", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleNotEqualTo(String value) {
			addCriterion("article_title <>", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleGreaterThan(String value) {
			addCriterion("article_title >", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
			addCriterion("article_title >=", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleLessThan(String value) {
			addCriterion("article_title <", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleLessThanOrEqualTo(String value) {
			addCriterion("article_title <=", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleLike(String value) {
			addCriterion("article_title like", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleNotLike(String value) {
			addCriterion("article_title not like", value, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleIn(List<String> values) {
			addCriterion("article_title in", values, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleNotIn(List<String> values) {
			addCriterion("article_title not in", values, "articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleBetween(String value1, String value2) {
			addCriterion("article_title between", value1, value2,
					"articleTitle");
			return (Criteria) this;
		}

		public Criteria andArticleTitleNotBetween(String value1, String value2) {
			addCriterion("article_title not between", value1, value2,
					"articleTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleIsNull() {
			addCriterion("seo_title is null");
			return (Criteria) this;
		}

		public Criteria andSeoTitleIsNotNull() {
			addCriterion("seo_title is not null");
			return (Criteria) this;
		}

		public Criteria andSeoTitleEqualTo(String value) {
			addCriterion("seo_title =", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleNotEqualTo(String value) {
			addCriterion("seo_title <>", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleGreaterThan(String value) {
			addCriterion("seo_title >", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleGreaterThanOrEqualTo(String value) {
			addCriterion("seo_title >=", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleLessThan(String value) {
			addCriterion("seo_title <", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleLessThanOrEqualTo(String value) {
			addCriterion("seo_title <=", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleLike(String value) {
			addCriterion("seo_title like", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleNotLike(String value) {
			addCriterion("seo_title not like", value, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleIn(List<String> values) {
			addCriterion("seo_title in", values, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleNotIn(List<String> values) {
			addCriterion("seo_title not in", values, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleBetween(String value1, String value2) {
			addCriterion("seo_title between", value1, value2, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoTitleNotBetween(String value1, String value2) {
			addCriterion("seo_title not between", value1, value2, "seoTitle");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordIsNull() {
			addCriterion("seo_keyword is null");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordIsNotNull() {
			addCriterion("seo_keyword is not null");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordEqualTo(String value) {
			addCriterion("seo_keyword =", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordNotEqualTo(String value) {
			addCriterion("seo_keyword <>", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordGreaterThan(String value) {
			addCriterion("seo_keyword >", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("seo_keyword >=", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordLessThan(String value) {
			addCriterion("seo_keyword <", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordLessThanOrEqualTo(String value) {
			addCriterion("seo_keyword <=", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordLike(String value) {
			addCriterion("seo_keyword like", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordNotLike(String value) {
			addCriterion("seo_keyword not like", value, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordIn(List<String> values) {
			addCriterion("seo_keyword in", values, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordNotIn(List<String> values) {
			addCriterion("seo_keyword not in", values, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordBetween(String value1, String value2) {
			addCriterion("seo_keyword between", value1, value2, "seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoKeywordNotBetween(String value1, String value2) {
			addCriterion("seo_keyword not between", value1, value2,
					"seoKeyword");
			return (Criteria) this;
		}

		public Criteria andSeoDescIsNull() {
			addCriterion("seo_desc is null");
			return (Criteria) this;
		}

		public Criteria andSeoDescIsNotNull() {
			addCriterion("seo_desc is not null");
			return (Criteria) this;
		}

		public Criteria andSeoDescEqualTo(String value) {
			addCriterion("seo_desc =", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescNotEqualTo(String value) {
			addCriterion("seo_desc <>", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescGreaterThan(String value) {
			addCriterion("seo_desc >", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescGreaterThanOrEqualTo(String value) {
			addCriterion("seo_desc >=", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescLessThan(String value) {
			addCriterion("seo_desc <", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescLessThanOrEqualTo(String value) {
			addCriterion("seo_desc <=", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescLike(String value) {
			addCriterion("seo_desc like", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescNotLike(String value) {
			addCriterion("seo_desc not like", value, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescIn(List<String> values) {
			addCriterion("seo_desc in", values, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescNotIn(List<String> values) {
			addCriterion("seo_desc not in", values, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescBetween(String value1, String value2) {
			addCriterion("seo_desc between", value1, value2, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andSeoDescNotBetween(String value1, String value2) {
			addCriterion("seo_desc not between", value1, value2, "seoDesc");
			return (Criteria) this;
		}

		public Criteria andTagIsNull() {
			addCriterion("tag is null");
			return (Criteria) this;
		}

		public Criteria andTagIsNotNull() {
			addCriterion("tag is not null");
			return (Criteria) this;
		}

		public Criteria andTagEqualTo(String value) {
			addCriterion("tag =", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotEqualTo(String value) {
			addCriterion("tag <>", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThan(String value) {
			addCriterion("tag >", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThanOrEqualTo(String value) {
			addCriterion("tag >=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThan(String value) {
			addCriterion("tag <", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThanOrEqualTo(String value) {
			addCriterion("tag <=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLike(String value) {
			addCriterion("tag like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotLike(String value) {
			addCriterion("tag not like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagIn(List<String> values) {
			addCriterion("tag in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotIn(List<String> values) {
			addCriterion("tag not in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagBetween(String value1, String value2) {
			addCriterion("tag between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotBetween(String value1, String value2) {
			addCriterion("tag not between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNull() {
			addCriterion("article_type is null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIsNotNull() {
			addCriterion("article_type is not null");
			return (Criteria) this;
		}

		public Criteria andArticleTypeEqualTo(Integer value) {
			addCriterion("article_type =", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotEqualTo(Integer value) {
			addCriterion("article_type <>", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThan(Integer value) {
			addCriterion("article_type >", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("article_type >=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThan(Integer value) {
			addCriterion("article_type <", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeLessThanOrEqualTo(Integer value) {
			addCriterion("article_type <=", value, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeIn(List<Integer> values) {
			addCriterion("article_type in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotIn(List<Integer> values) {
			addCriterion("article_type not in", values, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeBetween(Integer value1, Integer value2) {
			addCriterion("article_type between", value1, value2, "articleType");
			return (Criteria) this;
		}

		public Criteria andArticleTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("article_type not between", value1, value2,
					"articleType");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<String> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<String> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andSourceFromIsNull() {
			addCriterion("source_from is null");
			return (Criteria) this;
		}

		public Criteria andSourceFromIsNotNull() {
			addCriterion("source_from is not null");
			return (Criteria) this;
		}

		public Criteria andSourceFromEqualTo(String value) {
			addCriterion("source_from =", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromNotEqualTo(String value) {
			addCriterion("source_from <>", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromGreaterThan(String value) {
			addCriterion("source_from >", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromGreaterThanOrEqualTo(String value) {
			addCriterion("source_from >=", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromLessThan(String value) {
			addCriterion("source_from <", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromLessThanOrEqualTo(String value) {
			addCriterion("source_from <=", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromLike(String value) {
			addCriterion("source_from like", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromNotLike(String value) {
			addCriterion("source_from not like", value, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromIn(List<String> values) {
			addCriterion("source_from in", values, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromNotIn(List<String> values) {
			addCriterion("source_from not in", values, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromBetween(String value1, String value2) {
			addCriterion("source_from between", value1, value2, "sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceFromNotBetween(String value1, String value2) {
			addCriterion("source_from not between", value1, value2,
					"sourceFrom");
			return (Criteria) this;
		}

		public Criteria andSourceUrlIsNull() {
			addCriterion("source_url is null");
			return (Criteria) this;
		}

		public Criteria andSourceUrlIsNotNull() {
			addCriterion("source_url is not null");
			return (Criteria) this;
		}

		public Criteria andSourceUrlEqualTo(String value) {
			addCriterion("source_url =", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlNotEqualTo(String value) {
			addCriterion("source_url <>", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlGreaterThan(String value) {
			addCriterion("source_url >", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlGreaterThanOrEqualTo(String value) {
			addCriterion("source_url >=", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlLessThan(String value) {
			addCriterion("source_url <", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlLessThanOrEqualTo(String value) {
			addCriterion("source_url <=", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlLike(String value) {
			addCriterion("source_url like", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlNotLike(String value) {
			addCriterion("source_url not like", value, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlIn(List<String> values) {
			addCriterion("source_url in", values, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlNotIn(List<String> values) {
			addCriterion("source_url not in", values, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlBetween(String value1, String value2) {
			addCriterion("source_url between", value1, value2, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andSourceUrlNotBetween(String value1, String value2) {
			addCriterion("source_url not between", value1, value2, "sourceUrl");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagIsNull() {
			addCriterion("anonymity_flag is null");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagIsNotNull() {
			addCriterion("anonymity_flag is not null");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagEqualTo(String value) {
			addCriterion("anonymity_flag =", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagNotEqualTo(String value) {
			addCriterion("anonymity_flag <>", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagGreaterThan(String value) {
			addCriterion("anonymity_flag >", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagGreaterThanOrEqualTo(String value) {
			addCriterion("anonymity_flag >=", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagLessThan(String value) {
			addCriterion("anonymity_flag <", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagLessThanOrEqualTo(String value) {
			addCriterion("anonymity_flag <=", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagLike(String value) {
			addCriterion("anonymity_flag like", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagNotLike(String value) {
			addCriterion("anonymity_flag not like", value, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagIn(List<String> values) {
			addCriterion("anonymity_flag in", values, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagNotIn(List<String> values) {
			addCriterion("anonymity_flag not in", values, "anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagBetween(String value1, String value2) {
			addCriterion("anonymity_flag between", value1, value2,
					"anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAnonymityFlagNotBetween(String value1, String value2) {
			addCriterion("anonymity_flag not between", value1, value2,
					"anonymityFlag");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNull() {
			addCriterion("publish_status is null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNotNull() {
			addCriterion("publish_status is not null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusEqualTo(String value) {
			addCriterion("publish_status =", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotEqualTo(String value) {
			addCriterion("publish_status <>", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThan(String value) {
			addCriterion("publish_status >", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThanOrEqualTo(String value) {
			addCriterion("publish_status >=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThan(String value) {
			addCriterion("publish_status <", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThanOrEqualTo(String value) {
			addCriterion("publish_status <=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLike(String value) {
			addCriterion("publish_status like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotLike(String value) {
			addCriterion("publish_status not like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIn(List<String> values) {
			addCriterion("publish_status in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotIn(List<String> values) {
			addCriterion("publish_status not in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusBetween(String value1, String value2) {
			addCriterion("publish_status between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotBetween(String value1, String value2) {
			addCriterion("publish_status not between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIsNull() {
			addCriterion("check_status is null");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIsNotNull() {
			addCriterion("check_status is not null");
			return (Criteria) this;
		}

		public Criteria andCheckStatusEqualTo(Integer value) {
			addCriterion("check_status =", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotEqualTo(Integer value) {
			addCriterion("check_status <>", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusGreaterThan(Integer value) {
			addCriterion("check_status >", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("check_status >=", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusLessThan(Integer value) {
			addCriterion("check_status <", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusLessThanOrEqualTo(Integer value) {
			addCriterion("check_status <=", value, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusIn(List<Integer> values) {
			addCriterion("check_status in", values, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotIn(List<Integer> values) {
			addCriterion("check_status not in", values, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusBetween(Integer value1, Integer value2) {
			addCriterion("check_status between", value1, value2, "checkStatus");
			return (Criteria) this;
		}

		public Criteria andCheckStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("check_status not between", value1, value2,
					"checkStatus");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNull() {
			addCriterion("view_popedom is null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNotNull() {
			addCriterion("view_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomEqualTo(Integer value) {
			addCriterion("view_popedom =", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotEqualTo(Integer value) {
			addCriterion("view_popedom <>", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThan(Integer value) {
			addCriterion("view_popedom >", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_popedom >=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThan(Integer value) {
			addCriterion("view_popedom <", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThanOrEqualTo(Integer value) {
			addCriterion("view_popedom <=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIn(List<Integer> values) {
			addCriterion("view_popedom in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotIn(List<Integer> values) {
			addCriterion("view_popedom not in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom between", value1, value2, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom not between", value1, value2,
					"viewPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNull() {
			addCriterion("comment_popedom is null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNotNull() {
			addCriterion("comment_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomEqualTo(String value) {
			addCriterion("comment_popedom =", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotEqualTo(String value) {
			addCriterion("comment_popedom <>", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThan(String value) {
			addCriterion("comment_popedom >", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThanOrEqualTo(String value) {
			addCriterion("comment_popedom >=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThan(String value) {
			addCriterion("comment_popedom <", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThanOrEqualTo(String value) {
			addCriterion("comment_popedom <=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLike(String value) {
			addCriterion("comment_popedom like", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotLike(String value) {
			addCriterion("comment_popedom not like", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIn(List<String> values) {
			addCriterion("comment_popedom in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotIn(List<String> values) {
			addCriterion("comment_popedom not in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomBetween(String value1, String value2) {
			addCriterion("comment_popedom between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotBetween(String value1, String value2) {
			addCriterion("comment_popedom not between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIsNull() {
			addCriterion("publish_time is null");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIsNotNull() {
			addCriterion("publish_time is not null");
			return (Criteria) this;
		}

		public Criteria andPublishTimeEqualTo(Date value) {
			addCriterion("publish_time =", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotEqualTo(Date value) {
			addCriterion("publish_time <>", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeGreaterThan(Date value) {
			addCriterion("publish_time >", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("publish_time >=", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeLessThan(Date value) {
			addCriterion("publish_time <", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeLessThanOrEqualTo(Date value) {
			addCriterion("publish_time <=", value, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeIn(List<Date> values) {
			addCriterion("publish_time in", values, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotIn(List<Date> values) {
			addCriterion("publish_time not in", values, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeBetween(Date value1, Date value2) {
			addCriterion("publish_time between", value1, value2, "publishTime");
			return (Criteria) this;
		}

		public Criteria andPublishTimeNotBetween(Date value1, Date value2) {
			addCriterion("publish_time not between", value1, value2,
					"publishTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIsNull() {
			addCriterion("check_time is null");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIsNotNull() {
			addCriterion("check_time is not null");
			return (Criteria) this;
		}

		public Criteria andCheckTimeEqualTo(Date value) {
			addCriterion("check_time =", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotEqualTo(Date value) {
			addCriterion("check_time <>", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeGreaterThan(Date value) {
			addCriterion("check_time >", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("check_time >=", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeLessThan(Date value) {
			addCriterion("check_time <", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeLessThanOrEqualTo(Date value) {
			addCriterion("check_time <=", value, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeIn(List<Date> values) {
			addCriterion("check_time in", values, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotIn(List<Date> values) {
			addCriterion("check_time not in", values, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeBetween(Date value1, Date value2) {
			addCriterion("check_time between", value1, value2, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckTimeNotBetween(Date value1, Date value2) {
			addCriterion("check_time not between", value1, value2, "checkTime");
			return (Criteria) this;
		}

		public Criteria andCheckerNameIsNull() {
			addCriterion("checker_name is null");
			return (Criteria) this;
		}

		public Criteria andCheckerNameIsNotNull() {
			addCriterion("checker_name is not null");
			return (Criteria) this;
		}

		public Criteria andCheckerNameEqualTo(String value) {
			addCriterion("checker_name =", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameNotEqualTo(String value) {
			addCriterion("checker_name <>", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameGreaterThan(String value) {
			addCriterion("checker_name >", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameGreaterThanOrEqualTo(String value) {
			addCriterion("checker_name >=", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameLessThan(String value) {
			addCriterion("checker_name <", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameLessThanOrEqualTo(String value) {
			addCriterion("checker_name <=", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameLike(String value) {
			addCriterion("checker_name like", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameNotLike(String value) {
			addCriterion("checker_name not like", value, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameIn(List<String> values) {
			addCriterion("checker_name in", values, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameNotIn(List<String> values) {
			addCriterion("checker_name not in", values, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameBetween(String value1, String value2) {
			addCriterion("checker_name between", value1, value2, "checkerName");
			return (Criteria) this;
		}

		public Criteria andCheckerNameNotBetween(String value1, String value2) {
			addCriterion("checker_name not between", value1, value2,
					"checkerName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNull() {
			addCriterion("updater_name is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNotNull() {
			addCriterion("updater_name is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameEqualTo(String value) {
			addCriterion("updater_name =", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotEqualTo(String value) {
			addCriterion("updater_name <>", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThan(String value) {
			addCriterion("updater_name >", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
			addCriterion("updater_name >=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThan(String value) {
			addCriterion("updater_name <", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
			addCriterion("updater_name <=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLike(String value) {
			addCriterion("updater_name like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotLike(String value) {
			addCriterion("updater_name not like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIn(List<String> values) {
			addCriterion("updater_name in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotIn(List<String> values) {
			addCriterion("updater_name not in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameBetween(String value1, String value2) {
			addCriterion("updater_name between", value1, value2, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotBetween(String value1, String value2) {
			addCriterion("updater_name not between", value1, value2,
					"updaterName");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNull() {
			addCriterion("adder_name is null");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNotNull() {
			addCriterion("adder_name is not null");
			return (Criteria) this;
		}

		public Criteria andAdderNameEqualTo(String value) {
			addCriterion("adder_name =", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotEqualTo(String value) {
			addCriterion("adder_name <>", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThan(String value) {
			addCriterion("adder_name >", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
			addCriterion("adder_name >=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThan(String value) {
			addCriterion("adder_name <", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThanOrEqualTo(String value) {
			addCriterion("adder_name <=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLike(String value) {
			addCriterion("adder_name like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotLike(String value) {
			addCriterion("adder_name not like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameIn(List<String> values) {
			addCriterion("adder_name in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotIn(List<String> values) {
			addCriterion("adder_name not in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameBetween(String value1, String value2) {
			addCriterion("adder_name between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotBetween(String value1, String value2) {
			addCriterion("adder_name not between", value1, value2, "adderName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 14 20:05:40 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}