package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class AuthUrl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.REC_ID
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.URL
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.url_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String urlType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.USER_TYPE
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.USER_STATUS
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.url_comment
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String urlComment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.ADDER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.ADD_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.UPDATER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String updaterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_url.UPDATE_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.REC_ID
	 * @return  the value of auth_url.REC_ID
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.REC_ID
	 * @param recId  the value for auth_url.REC_ID
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.URL
	 * @return  the value of auth_url.URL
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.URL
	 * @param url  the value for auth_url.URL
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.url_type
	 * @return  the value of auth_url.url_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUrlType() {
		return urlType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.url_type
	 * @param urlType  the value for auth_url.url_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUrlType(String urlType) {
		this.urlType = urlType == null ? null : urlType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.USER_TYPE
	 * @return  the value of auth_url.USER_TYPE
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.USER_TYPE
	 * @param userType  the value for auth_url.USER_TYPE
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserType(String userType) {
		this.userType = userType == null ? null : userType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.USER_STATUS
	 * @return  the value of auth_url.USER_STATUS
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.USER_STATUS
	 * @param userStatus  the value for auth_url.USER_STATUS
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus == null ? null : userStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.url_comment
	 * @return  the value of auth_url.url_comment
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUrlComment() {
		return urlComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.url_comment
	 * @param urlComment  the value for auth_url.url_comment
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUrlComment(String urlComment) {
		this.urlComment = urlComment == null ? null : urlComment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.ADDER_NAME
	 * @return  the value of auth_url.ADDER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.ADDER_NAME
	 * @param adderName  the value for auth_url.ADDER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.ADD_TIME
	 * @return  the value of auth_url.ADD_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.ADD_TIME
	 * @param addTime  the value for auth_url.ADD_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.UPDATER_NAME
	 * @return  the value of auth_url.UPDATER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getUpdaterName() {
		return updaterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.UPDATER_NAME
	 * @param updaterName  the value for auth_url.UPDATER_NAME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUpdaterName(String updaterName) {
		this.updaterName = updaterName == null ? null : updaterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_url.UPDATE_TIME
	 * @return  the value of auth_url.UPDATE_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_url.UPDATE_TIME
	 * @param updateTime  the value for auth_url.UPDATE_TIME
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}