package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuthUrlExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public AuthUrlExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecIdIsNull() {
			addCriterion("REC_ID is null");
			return (Criteria) this;
		}

		public Criteria andRecIdIsNotNull() {
			addCriterion("REC_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRecIdEqualTo(Long value) {
			addCriterion("REC_ID =", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotEqualTo(Long value) {
			addCriterion("REC_ID <>", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThan(Long value) {
			addCriterion("REC_ID >", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThanOrEqualTo(Long value) {
			addCriterion("REC_ID >=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThan(Long value) {
			addCriterion("REC_ID <", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThanOrEqualTo(Long value) {
			addCriterion("REC_ID <=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdIn(List<Long> values) {
			addCriterion("REC_ID in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotIn(List<Long> values) {
			addCriterion("REC_ID not in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdBetween(Long value1, Long value2) {
			addCriterion("REC_ID between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotBetween(Long value1, Long value2) {
			addCriterion("REC_ID not between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("URL is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("URL is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("URL =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("URL <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("URL >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("URL >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("URL <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("URL <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("URL like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("URL not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("URL in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("URL not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("URL between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("URL not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlTypeIsNull() {
			addCriterion("url_type is null");
			return (Criteria) this;
		}

		public Criteria andUrlTypeIsNotNull() {
			addCriterion("url_type is not null");
			return (Criteria) this;
		}

		public Criteria andUrlTypeEqualTo(String value) {
			addCriterion("url_type =", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeNotEqualTo(String value) {
			addCriterion("url_type <>", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeGreaterThan(String value) {
			addCriterion("url_type >", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeGreaterThanOrEqualTo(String value) {
			addCriterion("url_type >=", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeLessThan(String value) {
			addCriterion("url_type <", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeLessThanOrEqualTo(String value) {
			addCriterion("url_type <=", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeLike(String value) {
			addCriterion("url_type like", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeNotLike(String value) {
			addCriterion("url_type not like", value, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeIn(List<String> values) {
			addCriterion("url_type in", values, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeNotIn(List<String> values) {
			addCriterion("url_type not in", values, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeBetween(String value1, String value2) {
			addCriterion("url_type between", value1, value2, "urlType");
			return (Criteria) this;
		}

		public Criteria andUrlTypeNotBetween(String value1, String value2) {
			addCriterion("url_type not between", value1, value2, "urlType");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNull() {
			addCriterion("USER_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNotNull() {
			addCriterion("USER_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeEqualTo(String value) {
			addCriterion("USER_TYPE =", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotEqualTo(String value) {
			addCriterion("USER_TYPE <>", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThan(String value) {
			addCriterion("USER_TYPE >", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
			addCriterion("USER_TYPE >=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThan(String value) {
			addCriterion("USER_TYPE <", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThanOrEqualTo(String value) {
			addCriterion("USER_TYPE <=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLike(String value) {
			addCriterion("USER_TYPE like", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotLike(String value) {
			addCriterion("USER_TYPE not like", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeIn(List<String> values) {
			addCriterion("USER_TYPE in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotIn(List<String> values) {
			addCriterion("USER_TYPE not in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeBetween(String value1, String value2) {
			addCriterion("USER_TYPE between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotBetween(String value1, String value2) {
			addCriterion("USER_TYPE not between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserStatusIsNull() {
			addCriterion("USER_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andUserStatusIsNotNull() {
			addCriterion("USER_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andUserStatusEqualTo(String value) {
			addCriterion("USER_STATUS =", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotEqualTo(String value) {
			addCriterion("USER_STATUS <>", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusGreaterThan(String value) {
			addCriterion("USER_STATUS >", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusGreaterThanOrEqualTo(String value) {
			addCriterion("USER_STATUS >=", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusLessThan(String value) {
			addCriterion("USER_STATUS <", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusLessThanOrEqualTo(String value) {
			addCriterion("USER_STATUS <=", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusLike(String value) {
			addCriterion("USER_STATUS like", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotLike(String value) {
			addCriterion("USER_STATUS not like", value, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusIn(List<String> values) {
			addCriterion("USER_STATUS in", values, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotIn(List<String> values) {
			addCriterion("USER_STATUS not in", values, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusBetween(String value1, String value2) {
			addCriterion("USER_STATUS between", value1, value2, "userStatus");
			return (Criteria) this;
		}

		public Criteria andUserStatusNotBetween(String value1, String value2) {
			addCriterion("USER_STATUS not between", value1, value2,
					"userStatus");
			return (Criteria) this;
		}

		public Criteria andUrlCommentIsNull() {
			addCriterion("url_comment is null");
			return (Criteria) this;
		}

		public Criteria andUrlCommentIsNotNull() {
			addCriterion("url_comment is not null");
			return (Criteria) this;
		}

		public Criteria andUrlCommentEqualTo(String value) {
			addCriterion("url_comment =", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentNotEqualTo(String value) {
			addCriterion("url_comment <>", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentGreaterThan(String value) {
			addCriterion("url_comment >", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentGreaterThanOrEqualTo(String value) {
			addCriterion("url_comment >=", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentLessThan(String value) {
			addCriterion("url_comment <", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentLessThanOrEqualTo(String value) {
			addCriterion("url_comment <=", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentLike(String value) {
			addCriterion("url_comment like", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentNotLike(String value) {
			addCriterion("url_comment not like", value, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentIn(List<String> values) {
			addCriterion("url_comment in", values, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentNotIn(List<String> values) {
			addCriterion("url_comment not in", values, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentBetween(String value1, String value2) {
			addCriterion("url_comment between", value1, value2, "urlComment");
			return (Criteria) this;
		}

		public Criteria andUrlCommentNotBetween(String value1, String value2) {
			addCriterion("url_comment not between", value1, value2,
					"urlComment");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNull() {
			addCriterion("ADDER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNotNull() {
			addCriterion("ADDER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAdderNameEqualTo(String value) {
			addCriterion("ADDER_NAME =", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotEqualTo(String value) {
			addCriterion("ADDER_NAME <>", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThan(String value) {
			addCriterion("ADDER_NAME >", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
			addCriterion("ADDER_NAME >=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThan(String value) {
			addCriterion("ADDER_NAME <", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThanOrEqualTo(String value) {
			addCriterion("ADDER_NAME <=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLike(String value) {
			addCriterion("ADDER_NAME like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotLike(String value) {
			addCriterion("ADDER_NAME not like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameIn(List<String> values) {
			addCriterion("ADDER_NAME in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotIn(List<String> values) {
			addCriterion("ADDER_NAME not in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameBetween(String value1, String value2) {
			addCriterion("ADDER_NAME between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotBetween(String value1, String value2) {
			addCriterion("ADDER_NAME not between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("ADD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("ADD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("ADD_TIME =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("ADD_TIME <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("ADD_TIME >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ADD_TIME >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("ADD_TIME <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("ADD_TIME <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("ADD_TIME in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("ADD_TIME not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("ADD_TIME between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("ADD_TIME not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNull() {
			addCriterion("UPDATER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNotNull() {
			addCriterion("UPDATER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameEqualTo(String value) {
			addCriterion("UPDATER_NAME =", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotEqualTo(String value) {
			addCriterion("UPDATER_NAME <>", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThan(String value) {
			addCriterion("UPDATER_NAME >", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATER_NAME >=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThan(String value) {
			addCriterion("UPDATER_NAME <", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
			addCriterion("UPDATER_NAME <=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLike(String value) {
			addCriterion("UPDATER_NAME like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotLike(String value) {
			addCriterion("UPDATER_NAME not like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIn(List<String> values) {
			addCriterion("UPDATER_NAME in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotIn(List<String> values) {
			addCriterion("UPDATER_NAME not in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameBetween(String value1, String value2) {
			addCriterion("UPDATER_NAME between", value1, value2, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotBetween(String value1, String value2) {
			addCriterion("UPDATER_NAME not between", value1, value2,
					"updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table auth_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_url
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 23 22:29:25 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}