package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class CardMap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.card_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.weight
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.frequency
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String frequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column card_map.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.rec_id
	 * @return  the value of card_map.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.rec_id
	 * @param recId  the value for card_map.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.user_id
	 * @return  the value of card_map.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.user_id
	 * @param userId  the value for card_map.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.card_id
	 * @return  the value of card_map.card_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.card_id
	 * @param cardId  the value for card_map.card_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.weight
	 * @return  the value of card_map.weight
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.weight
	 * @param weight  the value for card_map.weight
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.frequency
	 * @return  the value of card_map.frequency
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getFrequency() {
		return frequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.frequency
	 * @param frequency  the value for card_map.frequency
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setFrequency(String frequency) {
		this.frequency = frequency == null ? null : frequency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.remark
	 * @return  the value of card_map.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.remark
	 * @param remark  the value for card_map.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column card_map.rep_time
	 * @return  the value of card_map.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column card_map.rep_time
	 * @param repTime  the value for card_map.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}
}