package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClickNumExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public ClickNumExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecIdIsNull() {
			addCriterion("rec_id is null");
			return (Criteria) this;
		}

		public Criteria andRecIdIsNotNull() {
			addCriterion("rec_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecIdEqualTo(Long value) {
			addCriterion("rec_id =", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotEqualTo(Long value) {
			addCriterion("rec_id <>", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThan(Long value) {
			addCriterion("rec_id >", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdGreaterThanOrEqualTo(Long value) {
			addCriterion("rec_id >=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThan(Long value) {
			addCriterion("rec_id <", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdLessThanOrEqualTo(Long value) {
			addCriterion("rec_id <=", value, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdIn(List<Long> values) {
			addCriterion("rec_id in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotIn(List<Long> values) {
			addCriterion("rec_id not in", values, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdBetween(Long value1, Long value2) {
			addCriterion("rec_id between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andRecIdNotBetween(Long value1, Long value2) {
			addCriterion("rec_id not between", value1, value2, "recId");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIsNull() {
			addCriterion("object_type is null");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIsNotNull() {
			addCriterion("object_type is not null");
			return (Criteria) this;
		}

		public Criteria andObjectTypeEqualTo(Integer value) {
			addCriterion("object_type =", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotEqualTo(Integer value) {
			addCriterion("object_type <>", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeGreaterThan(Integer value) {
			addCriterion("object_type >", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("object_type >=", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeLessThan(Integer value) {
			addCriterion("object_type <", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("object_type <=", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIn(List<Integer> values) {
			addCriterion("object_type in", values, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotIn(List<Integer> values) {
			addCriterion("object_type not in", values, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeBetween(Integer value1, Integer value2) {
			addCriterion("object_type between", value1, value2, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("object_type not between", value1, value2,
					"objectType");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNull() {
			addCriterion("object_id is null");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNotNull() {
			addCriterion("object_id is not null");
			return (Criteria) this;
		}

		public Criteria andObjectIdEqualTo(Long value) {
			addCriterion("object_id =", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotEqualTo(Long value) {
			addCriterion("object_id <>", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThan(Long value) {
			addCriterion("object_id >", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("object_id >=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThan(Long value) {
			addCriterion("object_id <", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThanOrEqualTo(Long value) {
			addCriterion("object_id <=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdIn(List<Long> values) {
			addCriterion("object_id in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotIn(List<Long> values) {
			addCriterion("object_id not in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdBetween(Long value1, Long value2) {
			addCriterion("object_id between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotBetween(Long value1, Long value2) {
			addCriterion("object_id not between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andInitNumIsNull() {
			addCriterion("init_num is null");
			return (Criteria) this;
		}

		public Criteria andInitNumIsNotNull() {
			addCriterion("init_num is not null");
			return (Criteria) this;
		}

		public Criteria andInitNumEqualTo(Integer value) {
			addCriterion("init_num =", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumNotEqualTo(Integer value) {
			addCriterion("init_num <>", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumGreaterThan(Integer value) {
			addCriterion("init_num >", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("init_num >=", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumLessThan(Integer value) {
			addCriterion("init_num <", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumLessThanOrEqualTo(Integer value) {
			addCriterion("init_num <=", value, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumIn(List<Integer> values) {
			addCriterion("init_num in", values, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumNotIn(List<Integer> values) {
			addCriterion("init_num not in", values, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumBetween(Integer value1, Integer value2) {
			addCriterion("init_num between", value1, value2, "initNum");
			return (Criteria) this;
		}

		public Criteria andInitNumNotBetween(Integer value1, Integer value2) {
			addCriterion("init_num not between", value1, value2, "initNum");
			return (Criteria) this;
		}

		public Criteria andClickNumIsNull() {
			addCriterion("click_num is null");
			return (Criteria) this;
		}

		public Criteria andClickNumIsNotNull() {
			addCriterion("click_num is not null");
			return (Criteria) this;
		}

		public Criteria andClickNumEqualTo(Integer value) {
			addCriterion("click_num =", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumNotEqualTo(Integer value) {
			addCriterion("click_num <>", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumGreaterThan(Integer value) {
			addCriterion("click_num >", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("click_num >=", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumLessThan(Integer value) {
			addCriterion("click_num <", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumLessThanOrEqualTo(Integer value) {
			addCriterion("click_num <=", value, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumIn(List<Integer> values) {
			addCriterion("click_num in", values, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumNotIn(List<Integer> values) {
			addCriterion("click_num not in", values, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumBetween(Integer value1, Integer value2) {
			addCriterion("click_num between", value1, value2, "clickNum");
			return (Criteria) this;
		}

		public Criteria andClickNumNotBetween(Integer value1, Integer value2) {
			addCriterion("click_num not between", value1, value2, "clickNum");
			return (Criteria) this;
		}

		public Criteria andRepTimeIsNull() {
			addCriterion("rep_time is null");
			return (Criteria) this;
		}

		public Criteria andRepTimeIsNotNull() {
			addCriterion("rep_time is not null");
			return (Criteria) this;
		}

		public Criteria andRepTimeEqualTo(Date value) {
			addCriterion("rep_time =", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotEqualTo(Date value) {
			addCriterion("rep_time <>", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeGreaterThan(Date value) {
			addCriterion("rep_time >", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("rep_time >=", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeLessThan(Date value) {
			addCriterion("rep_time <", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeLessThanOrEqualTo(Date value) {
			addCriterion("rep_time <=", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeIn(List<Date> values) {
			addCriterion("rep_time in", values, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotIn(List<Date> values) {
			addCriterion("rep_time not in", values, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeBetween(Date value1, Date value2) {
			addCriterion("rep_time between", value1, value2, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotBetween(Date value1, Date value2) {
			addCriterion("rep_time not between", value1, value2, "repTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table click_num
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 14 20:05:40 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}