package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class ClickNum {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer objectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.init_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer initNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer clickNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column click_num.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.rec_id
	 * @return  the value of click_num.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.rec_id
	 * @param recId  the value for click_num.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.object_type
	 * @return  the value of click_num.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getObjectType() {
		return objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.object_type
	 * @param objectType  the value for click_num.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setObjectType(Integer objectType) {
		this.objectType = objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.object_id
	 * @return  the value of click_num.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.object_id
	 * @param objectId  the value for click_num.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.init_num
	 * @return  the value of click_num.init_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getInitNum() {
		return initNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.init_num
	 * @param initNum  the value for click_num.init_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setInitNum(Integer initNum) {
		this.initNum = initNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.click_num
	 * @return  the value of click_num.click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getClickNum() {
		return clickNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.click_num
	 * @param clickNum  the value for click_num.click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setClickNum(Integer clickNum) {
		this.clickNum = clickNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column click_num.rep_time
	 * @return  the value of click_num.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column click_num.rep_time
	 * @param repTime  the value for click_num.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}
}