package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class CommentList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.comment_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String objectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.assent_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer assentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.against_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer againstNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment_list.comment_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String commentStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.comment_id
	 * @return  the value of comment_list.comment_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.comment_id
	 * @param commentId  the value for comment_list.comment_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.object_type
	 * @return  the value of comment_list.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getObjectType() {
		return objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.object_type
	 * @param objectType  the value for comment_list.object_type
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setObjectType(String objectType) {
		this.objectType = objectType == null ? null : objectType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.object_id
	 * @return  the value of comment_list.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.object_id
	 * @param objectId  the value for comment_list.object_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.content
	 * @return  the value of comment_list.content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.content
	 * @param content  the value for comment_list.content
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.assent_num
	 * @return  the value of comment_list.assent_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getAssentNum() {
		return assentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.assent_num
	 * @param assentNum  the value for comment_list.assent_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAssentNum(Integer assentNum) {
		this.assentNum = assentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.against_num
	 * @return  the value of comment_list.against_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getAgainstNum() {
		return againstNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.against_num
	 * @param againstNum  the value for comment_list.against_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAgainstNum(Integer againstNum) {
		this.againstNum = againstNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.add_time
	 * @return  the value of comment_list.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.add_time
	 * @param addTime  the value for comment_list.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.rep_time
	 * @return  the value of comment_list.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.rep_time
	 * @param repTime  the value for comment_list.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment_list.comment_status
	 * @return  the value of comment_list.comment_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCommentStatus() {
		return commentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment_list.comment_status
	 * @param commentStatus  the value for comment_list.comment_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentStatus(String commentStatus) {
		this.commentStatus = commentStatus == null ? null : commentStatus
				.trim();
	}
}