package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentListExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public CommentListExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCommentIdIsNull() {
			addCriterion("comment_id is null");
			return (Criteria) this;
		}

		public Criteria andCommentIdIsNotNull() {
			addCriterion("comment_id is not null");
			return (Criteria) this;
		}

		public Criteria andCommentIdEqualTo(Long value) {
			addCriterion("comment_id =", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotEqualTo(Long value) {
			addCriterion("comment_id <>", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThan(Long value) {
			addCriterion("comment_id >", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("comment_id >=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThan(Long value) {
			addCriterion("comment_id <", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdLessThanOrEqualTo(Long value) {
			addCriterion("comment_id <=", value, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdIn(List<Long> values) {
			addCriterion("comment_id in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotIn(List<Long> values) {
			addCriterion("comment_id not in", values, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdBetween(Long value1, Long value2) {
			addCriterion("comment_id between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andCommentIdNotBetween(Long value1, Long value2) {
			addCriterion("comment_id not between", value1, value2, "commentId");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIsNull() {
			addCriterion("object_type is null");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIsNotNull() {
			addCriterion("object_type is not null");
			return (Criteria) this;
		}

		public Criteria andObjectTypeEqualTo(String value) {
			addCriterion("object_type =", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotEqualTo(String value) {
			addCriterion("object_type <>", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeGreaterThan(String value) {
			addCriterion("object_type >", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeGreaterThanOrEqualTo(String value) {
			addCriterion("object_type >=", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeLessThan(String value) {
			addCriterion("object_type <", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeLessThanOrEqualTo(String value) {
			addCriterion("object_type <=", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeLike(String value) {
			addCriterion("object_type like", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotLike(String value) {
			addCriterion("object_type not like", value, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeIn(List<String> values) {
			addCriterion("object_type in", values, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotIn(List<String> values) {
			addCriterion("object_type not in", values, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeBetween(String value1, String value2) {
			addCriterion("object_type between", value1, value2, "objectType");
			return (Criteria) this;
		}

		public Criteria andObjectTypeNotBetween(String value1, String value2) {
			addCriterion("object_type not between", value1, value2,
					"objectType");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNull() {
			addCriterion("object_id is null");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNotNull() {
			addCriterion("object_id is not null");
			return (Criteria) this;
		}

		public Criteria andObjectIdEqualTo(Long value) {
			addCriterion("object_id =", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotEqualTo(Long value) {
			addCriterion("object_id <>", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThan(Long value) {
			addCriterion("object_id >", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("object_id >=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThan(Long value) {
			addCriterion("object_id <", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThanOrEqualTo(Long value) {
			addCriterion("object_id <=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdIn(List<Long> values) {
			addCriterion("object_id in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotIn(List<Long> values) {
			addCriterion("object_id not in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdBetween(Long value1, Long value2) {
			addCriterion("object_id between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotBetween(Long value1, Long value2) {
			addCriterion("object_id not between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andAssentNumIsNull() {
			addCriterion("assent_num is null");
			return (Criteria) this;
		}

		public Criteria andAssentNumIsNotNull() {
			addCriterion("assent_num is not null");
			return (Criteria) this;
		}

		public Criteria andAssentNumEqualTo(Integer value) {
			addCriterion("assent_num =", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumNotEqualTo(Integer value) {
			addCriterion("assent_num <>", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumGreaterThan(Integer value) {
			addCriterion("assent_num >", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("assent_num >=", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumLessThan(Integer value) {
			addCriterion("assent_num <", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumLessThanOrEqualTo(Integer value) {
			addCriterion("assent_num <=", value, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumIn(List<Integer> values) {
			addCriterion("assent_num in", values, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumNotIn(List<Integer> values) {
			addCriterion("assent_num not in", values, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumBetween(Integer value1, Integer value2) {
			addCriterion("assent_num between", value1, value2, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAssentNumNotBetween(Integer value1, Integer value2) {
			addCriterion("assent_num not between", value1, value2, "assentNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumIsNull() {
			addCriterion("against_num is null");
			return (Criteria) this;
		}

		public Criteria andAgainstNumIsNotNull() {
			addCriterion("against_num is not null");
			return (Criteria) this;
		}

		public Criteria andAgainstNumEqualTo(Integer value) {
			addCriterion("against_num =", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumNotEqualTo(Integer value) {
			addCriterion("against_num <>", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumGreaterThan(Integer value) {
			addCriterion("against_num >", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("against_num >=", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumLessThan(Integer value) {
			addCriterion("against_num <", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumLessThanOrEqualTo(Integer value) {
			addCriterion("against_num <=", value, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumIn(List<Integer> values) {
			addCriterion("against_num in", values, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumNotIn(List<Integer> values) {
			addCriterion("against_num not in", values, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumBetween(Integer value1, Integer value2) {
			addCriterion("against_num between", value1, value2, "againstNum");
			return (Criteria) this;
		}

		public Criteria andAgainstNumNotBetween(Integer value1, Integer value2) {
			addCriterion("against_num not between", value1, value2,
					"againstNum");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeIsNull() {
			addCriterion("rep_time is null");
			return (Criteria) this;
		}

		public Criteria andRepTimeIsNotNull() {
			addCriterion("rep_time is not null");
			return (Criteria) this;
		}

		public Criteria andRepTimeEqualTo(Date value) {
			addCriterion("rep_time =", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotEqualTo(Date value) {
			addCriterion("rep_time <>", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeGreaterThan(Date value) {
			addCriterion("rep_time >", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("rep_time >=", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeLessThan(Date value) {
			addCriterion("rep_time <", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeLessThanOrEqualTo(Date value) {
			addCriterion("rep_time <=", value, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeIn(List<Date> values) {
			addCriterion("rep_time in", values, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotIn(List<Date> values) {
			addCriterion("rep_time not in", values, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeBetween(Date value1, Date value2) {
			addCriterion("rep_time between", value1, value2, "repTime");
			return (Criteria) this;
		}

		public Criteria andRepTimeNotBetween(Date value1, Date value2) {
			addCriterion("rep_time not between", value1, value2, "repTime");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIsNull() {
			addCriterion("comment_status is null");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIsNotNull() {
			addCriterion("comment_status is not null");
			return (Criteria) this;
		}

		public Criteria andCommentStatusEqualTo(String value) {
			addCriterion("comment_status =", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotEqualTo(String value) {
			addCriterion("comment_status <>", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusGreaterThan(String value) {
			addCriterion("comment_status >", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusGreaterThanOrEqualTo(String value) {
			addCriterion("comment_status >=", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLessThan(String value) {
			addCriterion("comment_status <", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLessThanOrEqualTo(String value) {
			addCriterion("comment_status <=", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusLike(String value) {
			addCriterion("comment_status like", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotLike(String value) {
			addCriterion("comment_status not like", value, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusIn(List<String> values) {
			addCriterion("comment_status in", values, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotIn(List<String> values) {
			addCriterion("comment_status not in", values, "commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusBetween(String value1, String value2) {
			addCriterion("comment_status between", value1, value2,
					"commentStatus");
			return (Criteria) this;
		}

		public Criteria andCommentStatusNotBetween(String value1, String value2) {
			addCriterion("comment_status not between", value1, value2,
					"commentStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment_list
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 14 20:05:40 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}