package com.focustech.cookinglove.ibator.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PhotoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public PhotoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPicIdIsNull() {
			addCriterion("pic_id is null");
			return (Criteria) this;
		}

		public Criteria andPicIdIsNotNull() {
			addCriterion("pic_id is not null");
			return (Criteria) this;
		}

		public Criteria andPicIdEqualTo(Long value) {
			addCriterion("pic_id =", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdNotEqualTo(Long value) {
			addCriterion("pic_id <>", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdGreaterThan(Long value) {
			addCriterion("pic_id >", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdGreaterThanOrEqualTo(Long value) {
			addCriterion("pic_id >=", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdLessThan(Long value) {
			addCriterion("pic_id <", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdLessThanOrEqualTo(Long value) {
			addCriterion("pic_id <=", value, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdIn(List<Long> values) {
			addCriterion("pic_id in", values, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdNotIn(List<Long> values) {
			addCriterion("pic_id not in", values, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdBetween(Long value1, Long value2) {
			addCriterion("pic_id between", value1, value2, "picId");
			return (Criteria) this;
		}

		public Criteria andPicIdNotBetween(Long value1, Long value2) {
			addCriterion("pic_id not between", value1, value2, "picId");
			return (Criteria) this;
		}

		public Criteria andPicNameIsNull() {
			addCriterion("pic_name is null");
			return (Criteria) this;
		}

		public Criteria andPicNameIsNotNull() {
			addCriterion("pic_name is not null");
			return (Criteria) this;
		}

		public Criteria andPicNameEqualTo(String value) {
			addCriterion("pic_name =", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameNotEqualTo(String value) {
			addCriterion("pic_name <>", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameGreaterThan(String value) {
			addCriterion("pic_name >", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameGreaterThanOrEqualTo(String value) {
			addCriterion("pic_name >=", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameLessThan(String value) {
			addCriterion("pic_name <", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameLessThanOrEqualTo(String value) {
			addCriterion("pic_name <=", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameLike(String value) {
			addCriterion("pic_name like", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameNotLike(String value) {
			addCriterion("pic_name not like", value, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameIn(List<String> values) {
			addCriterion("pic_name in", values, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameNotIn(List<String> values) {
			addCriterion("pic_name not in", values, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameBetween(String value1, String value2) {
			addCriterion("pic_name between", value1, value2, "picName");
			return (Criteria) this;
		}

		public Criteria andPicNameNotBetween(String value1, String value2) {
			addCriterion("pic_name not between", value1, value2, "picName");
			return (Criteria) this;
		}

		public Criteria andNormalPathIsNull() {
			addCriterion("normal_path is null");
			return (Criteria) this;
		}

		public Criteria andNormalPathIsNotNull() {
			addCriterion("normal_path is not null");
			return (Criteria) this;
		}

		public Criteria andNormalPathEqualTo(String value) {
			addCriterion("normal_path =", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathNotEqualTo(String value) {
			addCriterion("normal_path <>", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathGreaterThan(String value) {
			addCriterion("normal_path >", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathGreaterThanOrEqualTo(String value) {
			addCriterion("normal_path >=", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathLessThan(String value) {
			addCriterion("normal_path <", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathLessThanOrEqualTo(String value) {
			addCriterion("normal_path <=", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathLike(String value) {
			addCriterion("normal_path like", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathNotLike(String value) {
			addCriterion("normal_path not like", value, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathIn(List<String> values) {
			addCriterion("normal_path in", values, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathNotIn(List<String> values) {
			addCriterion("normal_path not in", values, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathBetween(String value1, String value2) {
			addCriterion("normal_path between", value1, value2, "normalPath");
			return (Criteria) this;
		}

		public Criteria andNormalPathNotBetween(String value1, String value2) {
			addCriterion("normal_path not between", value1, value2,
					"normalPath");
			return (Criteria) this;
		}

		public Criteria andBigPathIsNull() {
			addCriterion("big_path is null");
			return (Criteria) this;
		}

		public Criteria andBigPathIsNotNull() {
			addCriterion("big_path is not null");
			return (Criteria) this;
		}

		public Criteria andBigPathEqualTo(String value) {
			addCriterion("big_path =", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathNotEqualTo(String value) {
			addCriterion("big_path <>", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathGreaterThan(String value) {
			addCriterion("big_path >", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathGreaterThanOrEqualTo(String value) {
			addCriterion("big_path >=", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathLessThan(String value) {
			addCriterion("big_path <", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathLessThanOrEqualTo(String value) {
			addCriterion("big_path <=", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathLike(String value) {
			addCriterion("big_path like", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathNotLike(String value) {
			addCriterion("big_path not like", value, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathIn(List<String> values) {
			addCriterion("big_path in", values, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathNotIn(List<String> values) {
			addCriterion("big_path not in", values, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathBetween(String value1, String value2) {
			addCriterion("big_path between", value1, value2, "bigPath");
			return (Criteria) this;
		}

		public Criteria andBigPathNotBetween(String value1, String value2) {
			addCriterion("big_path not between", value1, value2, "bigPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathIsNull() {
			addCriterion("thumbnail_path is null");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathIsNotNull() {
			addCriterion("thumbnail_path is not null");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathEqualTo(String value) {
			addCriterion("thumbnail_path =", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathNotEqualTo(String value) {
			addCriterion("thumbnail_path <>", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathGreaterThan(String value) {
			addCriterion("thumbnail_path >", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathGreaterThanOrEqualTo(String value) {
			addCriterion("thumbnail_path >=", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathLessThan(String value) {
			addCriterion("thumbnail_path <", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathLessThanOrEqualTo(String value) {
			addCriterion("thumbnail_path <=", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathLike(String value) {
			addCriterion("thumbnail_path like", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathNotLike(String value) {
			addCriterion("thumbnail_path not like", value, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathIn(List<String> values) {
			addCriterion("thumbnail_path in", values, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathNotIn(List<String> values) {
			addCriterion("thumbnail_path not in", values, "thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathBetween(String value1, String value2) {
			addCriterion("thumbnail_path between", value1, value2,
					"thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andThumbnailPathNotBetween(String value1, String value2) {
			addCriterion("thumbnail_path not between", value1, value2,
					"thumbnailPath");
			return (Criteria) this;
		}

		public Criteria andAltTextIsNull() {
			addCriterion("alt_text is null");
			return (Criteria) this;
		}

		public Criteria andAltTextIsNotNull() {
			addCriterion("alt_text is not null");
			return (Criteria) this;
		}

		public Criteria andAltTextEqualTo(String value) {
			addCriterion("alt_text =", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextNotEqualTo(String value) {
			addCriterion("alt_text <>", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextGreaterThan(String value) {
			addCriterion("alt_text >", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextGreaterThanOrEqualTo(String value) {
			addCriterion("alt_text >=", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextLessThan(String value) {
			addCriterion("alt_text <", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextLessThanOrEqualTo(String value) {
			addCriterion("alt_text <=", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextLike(String value) {
			addCriterion("alt_text like", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextNotLike(String value) {
			addCriterion("alt_text not like", value, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextIn(List<String> values) {
			addCriterion("alt_text in", values, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextNotIn(List<String> values) {
			addCriterion("alt_text not in", values, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextBetween(String value1, String value2) {
			addCriterion("alt_text between", value1, value2, "altText");
			return (Criteria) this;
		}

		public Criteria andAltTextNotBetween(String value1, String value2) {
			addCriterion("alt_text not between", value1, value2, "altText");
			return (Criteria) this;
		}

		public Criteria andTitleTextIsNull() {
			addCriterion("title_text is null");
			return (Criteria) this;
		}

		public Criteria andTitleTextIsNotNull() {
			addCriterion("title_text is not null");
			return (Criteria) this;
		}

		public Criteria andTitleTextEqualTo(String value) {
			addCriterion("title_text =", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextNotEqualTo(String value) {
			addCriterion("title_text <>", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextGreaterThan(String value) {
			addCriterion("title_text >", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextGreaterThanOrEqualTo(String value) {
			addCriterion("title_text >=", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextLessThan(String value) {
			addCriterion("title_text <", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextLessThanOrEqualTo(String value) {
			addCriterion("title_text <=", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextLike(String value) {
			addCriterion("title_text like", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextNotLike(String value) {
			addCriterion("title_text not like", value, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextIn(List<String> values) {
			addCriterion("title_text in", values, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextNotIn(List<String> values) {
			addCriterion("title_text not in", values, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextBetween(String value1, String value2) {
			addCriterion("title_text between", value1, value2, "titleText");
			return (Criteria) this;
		}

		public Criteria andTitleTextNotBetween(String value1, String value2) {
			addCriterion("title_text not between", value1, value2, "titleText");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNull() {
			addCriterion("view_popedom is null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIsNotNull() {
			addCriterion("view_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andViewPopedomEqualTo(Integer value) {
			addCriterion("view_popedom =", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotEqualTo(Integer value) {
			addCriterion("view_popedom <>", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThan(Integer value) {
			addCriterion("view_popedom >", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomGreaterThanOrEqualTo(Integer value) {
			addCriterion("view_popedom >=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThan(Integer value) {
			addCriterion("view_popedom <", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomLessThanOrEqualTo(Integer value) {
			addCriterion("view_popedom <=", value, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomIn(List<Integer> values) {
			addCriterion("view_popedom in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotIn(List<Integer> values) {
			addCriterion("view_popedom not in", values, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom between", value1, value2, "viewPopedom");
			return (Criteria) this;
		}

		public Criteria andViewPopedomNotBetween(Integer value1, Integer value2) {
			addCriterion("view_popedom not between", value1, value2,
					"viewPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNull() {
			addCriterion("COMMENT_popedom is null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIsNotNull() {
			addCriterion("COMMENT_popedom is not null");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomEqualTo(Integer value) {
			addCriterion("COMMENT_popedom =", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotEqualTo(Integer value) {
			addCriterion("COMMENT_popedom <>", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThan(Integer value) {
			addCriterion("COMMENT_popedom >", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomGreaterThanOrEqualTo(Integer value) {
			addCriterion("COMMENT_popedom >=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThan(Integer value) {
			addCriterion("COMMENT_popedom <", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomLessThanOrEqualTo(Integer value) {
			addCriterion("COMMENT_popedom <=", value, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomIn(List<Integer> values) {
			addCriterion("COMMENT_popedom in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotIn(List<Integer> values) {
			addCriterion("COMMENT_popedom not in", values, "commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomBetween(Integer value1, Integer value2) {
			addCriterion("COMMENT_popedom between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andCommentPopedomNotBetween(Integer value1,
				Integer value2) {
			addCriterion("COMMENT_popedom not between", value1, value2,
					"commentPopedom");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNull() {
			addCriterion("publish_status is null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIsNotNull() {
			addCriterion("publish_status is not null");
			return (Criteria) this;
		}

		public Criteria andPublishStatusEqualTo(String value) {
			addCriterion("publish_status =", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotEqualTo(String value) {
			addCriterion("publish_status <>", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThan(String value) {
			addCriterion("publish_status >", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusGreaterThanOrEqualTo(String value) {
			addCriterion("publish_status >=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThan(String value) {
			addCriterion("publish_status <", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLessThanOrEqualTo(String value) {
			addCriterion("publish_status <=", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusLike(String value) {
			addCriterion("publish_status like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotLike(String value) {
			addCriterion("publish_status not like", value, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusIn(List<String> values) {
			addCriterion("publish_status in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotIn(List<String> values) {
			addCriterion("publish_status not in", values, "publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusBetween(String value1, String value2) {
			addCriterion("publish_status between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andPublishStatusNotBetween(String value1, String value2) {
			addCriterion("publish_status not between", value1, value2,
					"publishStatus");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIsNull() {
			addCriterion("comment_anonymity_flag is null");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIsNotNull() {
			addCriterion("comment_anonymity_flag is not null");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagEqualTo(String value) {
			addCriterion("comment_anonymity_flag =", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotEqualTo(String value) {
			addCriterion("comment_anonymity_flag <>", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagGreaterThan(String value) {
			addCriterion("comment_anonymity_flag >", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagGreaterThanOrEqualTo(String value) {
			addCriterion("comment_anonymity_flag >=", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLessThan(String value) {
			addCriterion("comment_anonymity_flag <", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLessThanOrEqualTo(String value) {
			addCriterion("comment_anonymity_flag <=", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagLike(String value) {
			addCriterion("comment_anonymity_flag like", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotLike(String value) {
			addCriterion("comment_anonymity_flag not like", value,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagIn(List<String> values) {
			addCriterion("comment_anonymity_flag in", values,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotIn(List<String> values) {
			addCriterion("comment_anonymity_flag not in", values,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagBetween(String value1,
				String value2) {
			addCriterion("comment_anonymity_flag between", value1, value2,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andCommentAnonymityFlagNotBetween(String value1,
				String value2) {
			addCriterion("comment_anonymity_flag not between", value1, value2,
					"commentAnonymityFlag");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photo
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 14 20:05:40 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}