package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class Photo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.pic_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long picId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.pic_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String picName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.normal_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String normalPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.big_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String bigPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.thumbnail_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String thumbnailPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.alt_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String altText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.title_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String titleText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer viewPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.COMMENT_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Integer commentPopedom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String publishStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String commentAnonymityFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column photo.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.pic_id
	 * @return  the value of photo.pic_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getPicId() {
		return picId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.pic_id
	 * @param picId  the value for photo.pic_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPicId(Long picId) {
		this.picId = picId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.pic_name
	 * @return  the value of photo.pic_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getPicName() {
		return picName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.pic_name
	 * @param picName  the value for photo.pic_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPicName(String picName) {
		this.picName = picName == null ? null : picName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.normal_path
	 * @return  the value of photo.normal_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getNormalPath() {
		return normalPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.normal_path
	 * @param normalPath  the value for photo.normal_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setNormalPath(String normalPath) {
		this.normalPath = normalPath == null ? null : normalPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.big_path
	 * @return  the value of photo.big_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getBigPath() {
		return bigPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.big_path
	 * @param bigPath  the value for photo.big_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setBigPath(String bigPath) {
		this.bigPath = bigPath == null ? null : bigPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.thumbnail_path
	 * @return  the value of photo.thumbnail_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getThumbnailPath() {
		return thumbnailPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.thumbnail_path
	 * @param thumbnailPath  the value for photo.thumbnail_path
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setThumbnailPath(String thumbnailPath) {
		this.thumbnailPath = thumbnailPath == null ? null : thumbnailPath
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.alt_text
	 * @return  the value of photo.alt_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAltText() {
		return altText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.alt_text
	 * @param altText  the value for photo.alt_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAltText(String altText) {
		this.altText = altText == null ? null : altText.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.title_text
	 * @return  the value of photo.title_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getTitleText() {
		return titleText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.title_text
	 * @param titleText  the value for photo.title_text
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setTitleText(String titleText) {
		this.titleText = titleText == null ? null : titleText.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.view_popedom
	 * @return  the value of photo.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getViewPopedom() {
		return viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.view_popedom
	 * @param viewPopedom  the value for photo.view_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setViewPopedom(Integer viewPopedom) {
		this.viewPopedom = viewPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.COMMENT_popedom
	 * @return  the value of photo.COMMENT_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Integer getCommentPopedom() {
		return commentPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.COMMENT_popedom
	 * @param commentPopedom  the value for photo.COMMENT_popedom
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentPopedom(Integer commentPopedom) {
		this.commentPopedom = commentPopedom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.publish_status
	 * @return  the value of photo.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getPublishStatus() {
		return publishStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.publish_status
	 * @param publishStatus  the value for photo.publish_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setPublishStatus(String publishStatus) {
		this.publishStatus = publishStatus == null ? null : publishStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.comment_anonymity_flag
	 * @return  the value of photo.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCommentAnonymityFlag() {
		return commentAnonymityFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.comment_anonymity_flag
	 * @param commentAnonymityFlag  the value for photo.comment_anonymity_flag
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCommentAnonymityFlag(String commentAnonymityFlag) {
		this.commentAnonymityFlag = commentAnonymityFlag == null ? null
				: commentAnonymityFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column photo.add_time
	 * @return  the value of photo.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column photo.add_time
	 * @param addTime  the value for photo.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
}