package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long resourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.resource_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String resourceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.parent_resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long parentResourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.resource_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String resourceUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.resource_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String resourceStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.resource_id
	 * @return  the value of resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.resource_id
	 * @param resourceId  the value for resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.resource_name
	 * @return  the value of resource.resource_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getResourceName() {
		return resourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.resource_name
	 * @param resourceName  the value for resource.resource_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setResourceName(String resourceName) {
		this.resourceName = resourceName == null ? null : resourceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.parent_resource_id
	 * @return  the value of resource.parent_resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getParentResourceId() {
		return parentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.parent_resource_id
	 * @param parentResourceId  the value for resource.parent_resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setParentResourceId(Long parentResourceId) {
		this.parentResourceId = parentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.resource_url
	 * @return  the value of resource.resource_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getResourceUrl() {
		return resourceUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.resource_url
	 * @param resourceUrl  the value for resource.resource_url
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.resource_status
	 * @return  the value of resource.resource_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getResourceStatus() {
		return resourceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.resource_status
	 * @param resourceStatus  the value for resource.resource_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setResourceStatus(String resourceStatus) {
		this.resourceStatus = resourceStatus == null ? null : resourceStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.add_time
	 * @return  the value of resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.add_time
	 * @param addTime  the value for resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.rep_time
	 * @return  the value of resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.rep_time
	 * @param repTime  the value for resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}
}