package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_id
	 * @return  the value of role.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_id
	 * @param roleId  the value for role.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
	 * @return  the value of role.role_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
	 * @param roleName  the value for role.role_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.remark
	 * @return  the value of role.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.remark
	 * @param remark  the value for role.remark
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.adder_name
	 * @return  the value of role.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.adder_name
	 * @param adderName  the value for role.adder_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.add_time
	 * @return  the value of role.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.add_time
	 * @param addTime  the value for role.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(String addTime) {
		this.addTime = addTime == null ? null : addTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.rep_time
	 * @return  the value of role.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.rep_time
	 * @param repTime  the value for role.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}
}