package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class RoleResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resource.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resource.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long resourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date repTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resource.rec_id
	 * @return  the value of role_resource.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resource.rec_id
	 * @param recId  the value for role_resource.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resource.role_id
	 * @return  the value of role_resource.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resource.role_id
	 * @param roleId  the value for role_resource.role_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resource.resource_id
	 * @return  the value of role_resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resource.resource_id
	 * @param resourceId  the value for role_resource.resource_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resource.add_time
	 * @return  the value of role_resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resource.add_time
	 * @param addTime  the value for role_resource.add_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_resource.rep_time
	 * @return  the value of role_resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getRepTime() {
		return repTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_resource.rep_time
	 * @param repTime  the value for role_resource.rep_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}
}