package com.focustech.cookinglove.ibator.domain;

import java.util.Date;

public class UserCard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long recId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.real_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.gender
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.graduate_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String graduateFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.company_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.job_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.card_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String cardStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.mobile
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.telphone
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_card.last_update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	private Date lastUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.rec_id
	 * @return  the value of user_card.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getRecId() {
		return recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.rec_id
	 * @param recId  the value for user_card.rec_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRecId(Long recId) {
		this.recId = recId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.user_id
	 * @return  the value of user_card.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.user_id
	 * @param userId  the value for user_card.user_id
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.real_name
	 * @return  the value of user_card.real_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.real_name
	 * @param realName  the value for user_card.real_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.gender
	 * @return  the value of user_card.gender
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.gender
	 * @param gender  the value for user_card.gender
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.graduate_from
	 * @return  the value of user_card.graduate_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getGraduateFrom() {
		return graduateFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.graduate_from
	 * @param graduateFrom  the value for user_card.graduate_from
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setGraduateFrom(String graduateFrom) {
		this.graduateFrom = graduateFrom == null ? null : graduateFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.company_name
	 * @return  the value of user_card.company_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.company_name
	 * @param companyName  the value for user_card.company_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName == null ? null : companyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.job_name
	 * @return  the value of user_card.job_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.job_name
	 * @param jobName  the value for user_card.job_name
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName == null ? null : jobName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.card_status
	 * @return  the value of user_card.card_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getCardStatus() {
		return cardStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.card_status
	 * @param cardStatus  the value for user_card.card_status
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus == null ? null : cardStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.mobile
	 * @return  the value of user_card.mobile
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.mobile
	 * @param mobile  the value for user_card.mobile
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.telphone
	 * @return  the value of user_card.telphone
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.telphone
	 * @param telphone  the value for user_card.telphone
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone == null ? null : telphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_card.last_update_time
	 * @return  the value of user_card.last_update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_card.last_update_time
	 * @param lastUpdateTime  the value for user_card.last_update_time
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}
}