package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.CardMap;
import com.focustech.cookinglove.ibator.domain.CardMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardMapMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(CardMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(CardMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(CardMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(CardMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<CardMap> selectByExample(CardMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	CardMap selectByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CardMap record,
			@Param("example") CardMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") CardMap record,
			@Param("example") CardMapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(CardMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table card_map
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(CardMap record);
}