package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.ClickNum;
import com.focustech.cookinglove.ibator.domain.ClickNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClickNumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(ClickNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(ClickNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(ClickNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(ClickNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<ClickNum> selectByExample(ClickNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	ClickNum selectByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") ClickNum record,
			@Param("example") ClickNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") ClickNum record,
			@Param("example") ClickNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(ClickNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table click_num
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(ClickNum record);
}