package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.CommentList;
import com.focustech.cookinglove.ibator.domain.CommentListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(CommentListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(CommentListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(CommentList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(CommentList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<CommentList> selectByExample(CommentListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	CommentList selectByPrimaryKey(Long commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CommentList record,
			@Param("example") CommentListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") CommentList record,
			@Param("example") CommentListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(CommentList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment_list
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(CommentList record);
}