package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.CoreLogonInfo;
import com.focustech.cookinglove.ibator.domain.CoreLogonInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoreLogonInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(CoreLogonInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(CoreLogonInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(CoreLogonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(CoreLogonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<CoreLogonInfo> selectByExample(CoreLogonInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	CoreLogonInfo selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CoreLogonInfo record,
			@Param("example") CoreLogonInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") CoreLogonInfo record,
			@Param("example") CoreLogonInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(CoreLogonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table core_logon_info
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(CoreLogonInfo record);
}