package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.Photo;
import com.focustech.cookinglove.ibator.domain.PhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(PhotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(PhotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long picId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<Photo> selectByExample(PhotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	Photo selectByPrimaryKey(Long picId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") Photo record,
			@Param("example") PhotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") Photo record,
			@Param("example") PhotoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table photo
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(Photo record);
}