package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.Resource;
import com.focustech.cookinglove.ibator.domain.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long resourceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<Resource> selectByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	Resource selectByPrimaryKey(Long resourceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") Resource record,
			@Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") Resource record,
			@Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(Resource record);
}