package com.focustech.cookinglove.ibator.mapper;

import com.focustech.cookinglove.ibator.domain.UserCard;
import com.focustech.cookinglove.ibator.domain.UserCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int countByExample(UserCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByExample(UserCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int deleteByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insert(UserCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int insertSelective(UserCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	List<UserCard> selectByExample(UserCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	UserCard selectByPrimaryKey(Long recId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExampleSelective(@Param("record") UserCard record,
			@Param("example") UserCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByExample(@Param("record") UserCard record,
			@Param("example") UserCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKeySelective(UserCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_card
	 * @mbggenerated  Tue Nov 27 21:19:28 CST 2012
	 */
	int updateByPrimaryKey(UserCard record);
}